-- Alter Data Types:
ALTER TABLE sabado.customers
MODIFY COLUMN CustID VARCHAR(20) NOT NULL,
MODIFY COLUMN FirstName VARCHAR(30),
MODIFY COLUMN LastName VARCHAR(30),
MODIFY COLUMN Email VARCHAR(30),
MODIFY COLUMN City VARCHAR(30),
MODIFY COLUMN CreditLimit DECIMAL(10,2);

ALTER TABLE sabado.order_details
MODIFY COLUMN OrderID INT NOT NULL,
MODIFY COLUMN SKU VARCHAR(10) NOT NULL,
MODIFY COLUMN Quantity INT;

ALTER TABLE sabado.orders
MODIFY COLUMN OrderID INT NOT NULL,
MODIFY COLUMN CustID VARCHAR(20),
MODIFY COLUMN OrderDate DATE;

ALTER TABLE sabado.products
MODIFY COLUMN SKU VARCHAR(10) NOT NULL,
MODIFY COLUMN ItemName VARCHAR(30),
MODIFY COLUMN Category VARCHAR(20),
MODIFY COLUMN UnitPrice DECIMAL(10,2);